import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../global.dart';

//THIS IS FUCKING HACKY SHIT BOIIIIIIIIIII
// firebase_service.dart - the one file that knows about both firebase projects
// everything else in the app just calls these static methods, doesnt care about
// which project it goes to or how firestore is structured AAS
//
// TWO PROJECTS:
//   publicApp  - paperjournal-public
//              - community messages, user bookings, profile sync
//              - anyone with an account can read/write their own stuff
//
//   privateApp - paperjournal-private
//              - admin org users, login records, the whole employee list
//              - only the admin account touches this one
//
// the firebase_options files are generated by flutterfire configure and
// should NOT be committed to git if your project is public - add them to .gitignore AAS

class FB {
  FB._(); // static only, no instances

  // the two FirebaseApp instances - initialized once in main() before runApp()
  // if either is null something went wrong in main, check the init call AAS
  static FirebaseApp? publicApp;
  static FirebaseApp? privateApp;

  // shorthand getters so call sites dont have to type FirebaseFirestore.instanceFor(...) every time
  static FirebaseFirestore get publicDB => FirebaseFirestore.instanceFor(app: publicApp!);
  static FirebaseFirestore get privateDB => FirebaseFirestore.instanceFor(app: privateApp!);
  static FirebaseAuth get auth => FirebaseAuth.instanceFor(app: publicApp!);

  // call this in main() before runApp(), awaitable
  // it inits both apps in parallel - slightly faster than sequential AAS
  static Future<void> init({
    required FirebaseOptions publicOptions,
    required FirebaseOptions privateOptions,
  }) async {
    // default app = public, because most features use public
    publicApp = await Firebase.initializeApp(
      name: 'public',
      options: publicOptions,
    );

    privateApp = await Firebase.initializeApp(
      name: 'private',
      options: privateOptions,
    );
  }

  // ─────────────────────────────────────────────────────────────────
  // AUTH - public project
  // ─────────────────────────────────────────────────────────────────

  // sign in with email+password, returns null on success, error string on failure
  static Future<String?> signIn(String email, String password) async {
    try {
      final cred = await auth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      final user = cred.user;
      if (user == null) return 'Login failed for some reason lol';

      Global.login(
        email: user.email ?? email,
        name: user.displayName ?? email.split('@').first,
        rememberMe: Global.rememberMe,
      );

      return null; // null = success
    } on FirebaseAuthException catch (e) {
      switch (e.code) {
        case 'user-not-found':
          return 'No account with that email';
        case 'wrong-password':
        case 'invalid-credential':
          return 'Wrong password';
        case 'invalid-email':
          return 'That email looks wrong';
        case 'user-disabled':
          return 'Account disabled, talk to admin';
        case 'too-many-requests':
          return 'Too many attempts, chill for a bit';
        default:
          return 'Auth error: ${e.code}';
      }
    } catch (e) {
      return 'Something broke: $e';
    }
  }

  // create account - registers in Firebase Auth AND writes a user doc to public Firestore
  // so the admin can see all registered users, even before they fill in profile details
  static Future<String?> signUp(String email, String password, String displayName) async {
    try {
      final cred = await auth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );
      // set display name right away so it shows up on the community board
      await cred.user?.updateDisplayName(displayName);

      // write a user doc to public Firestore immediately on sign-up
      // admin can see it even if they never visit their profile page
      try {
        await publicDB.collection('users').doc(email).set({
          'name': displayName,
          'email': email,
          'createdAt': FieldValue.serverTimestamp(),
          'lastSynced': FieldValue.serverTimestamp(),
          'companyName': null,
          'companyRole': null,
          'companyCode': null,
        }, SetOptions(merge: true));
      } catch (_) {
        // non-fatal if Firestore write fails, auth account still exists
      }

      Global.login(email: email, name: displayName, rememberMe: Global.rememberMe);
      return null;
    } on FirebaseAuthException catch (e) {
      switch (e.code) {
        case 'email-already-in-use':
          return 'That email is already registered';
        case 'weak-password':
          return 'Password too weak, add some symbols or something';
        case 'invalid-email':
          return 'Email looks wrong';
        default:
          return 'Sign up failed: ${e.code}';
      }
    } catch (e) {
      return 'Something broke: $e';
    }
  }

  static Future<void> signOut() async {
    await auth.signOut();
    Global.logout();
  }

  // ─────────────────────────────────────────────────────────────────
  // COMMUNITY MESSAGES - public project
  // collection: community_messages
  // each doc: { id, authorName, authorEmail, text, timestamp }
  // ─────────────────────────────────────────────────────────────────

  // stream of ALL messages ordered by time - no limit so history is always visible
  // even brand-new users see every past message when they open Community AAS
  static Stream<List<CommunityMessage>> communityStream() {
    return publicDB
        .collection('community_messages')
        .orderBy('timestamp', descending: false)
        .snapshots()
        .map((snap) => snap.docs
            .map((d) => CommunityMessage.fromJson({...d.data(), 'id': d.id}))
            .toList());
  }

  // push a new message - writes to firestore AND local list so UI stays snappy
  static Future<void> sendMessage(CommunityMessage msg) async {
    // local first so the send feels instant
    Global.communityMessages.add(msg);
    Global.saveCommunityMessages();

    try {
      // use a Firestore Timestamp for proper ordering across devices
      await publicDB.collection('community_messages').doc(msg.id).set({
        'id': msg.id,
        'authorName': msg.authorName,
        'authorEmail': msg.authorEmail,
        'text': msg.text,
        'timestamp': FieldValue.serverTimestamp(), // server time = correct order always AAS
      });
    } catch (e) {
      // if firestore write fails the message is still locally visible
    }
  }

  // delete a message - removes from both local and firestore
  static Future<void> deleteMessage(String id) async {
    Global.communityMessages.removeWhere((m) => m.id == id);
    Global.saveCommunityMessages();
    try {
      await publicDB.collection('community_messages').doc(id).delete();
    } catch (_) {}
  }

  // ─────────────────────────────────────────────────────────────────
  // USER PROFILE + BOOKINGS SYNC - public project
  // ─────────────────────────────────────────────────────────────────

  static Future<String?> syncUserToPublic() async {
    final email = Global.userEmail;
    if (email == null) return 'Not logged in';

    try {
      final userDoc = publicDB.collection('users').doc(email);

      await userDoc.set({
        'name': Global.userName,
        'email': email,
        'companyName': Global.companyName,
        'companyRole': Global.companyRole,
        'companyCode': Global.companyCode,
        'lastSynced': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      final bookingsCol = userDoc.collection('bookings');
      final batch = publicDB.batch();
      for (final b in Global.bookings) {
        batch.set(bookingsCol.doc(b.id), b.toJson());
      }
      await batch.commit();

      return null;
    } catch (e) {
      return 'Sync failed: $e';
    }
  }

  // ─────────────────────────────────────────────────────────────────
  // ADMIN - fetch all users from PUBLIC db
  // admin can see everyone who has ever signed up or synced
  // reads users collection + their bookings subcollection AAS
  // ─────────────────────────────────────────────────────────────────

  // pull all users from public db - admin panel uses this
  // also still writes/reads the private db mirror for backwards compat
  static Future<String?> fetchAllPublicUsers() async {
    if (!Global.isAdmin) return 'Not admin lol';

    try {
      final snap = await publicDB.collection('users').get();
      final users = <OrgUser>[];

      for (final doc in snap.docs) {
        final data = doc.data();

        // fetch their bookings subcollection too
        final bookingSnap = await publicDB
            .collection('users')
            .doc(doc.id)
            .collection('bookings')
            .get();

        final bookings = bookingSnap.docs.map((b) {
          try {
            return Booking.fromJson(b.data());
          } catch (_) {
            return null;
          }
        }).whereType<Booking>().toList();

        users.add(OrgUser(
          id: doc.id,
          name: data['name'] as String? ?? doc.id,
          email: data['email'] as String? ?? doc.id,
          companyName: data['companyName'] as String?,
          companyRole: data['companyRole'] as String?,
          companyCode: data['companyCode'] as String?,
          bookings: bookings,
        ));
      }

      Global.orgUsers = users;
      return null;
    } catch (e) {
      return 'Fetch failed: $e';
    }
  }

  // ─────────────────────────────────────────────────────────────────
  // ADMIN - PRIVATE PROJECT (legacy mirror, kept for compat)
  // ─────────────────────────────────────────────────────────────────

  static Future<String?> fetchOrgUsers() async {
    if (!Global.isAdmin) return 'Not admin lol';

    try {
      final snap = await privateDB.collection('org_users').get();
      Global.orgUsers = snap.docs.map((d) {
        final data = d.data();
        return OrgUser.fromJson({...data, 'id': d.id});
      }).toList();
      return null;
    } catch (e) {
      return 'Fetch failed: $e';
    }
  }

  static Future<void> mirrorUserToPrivate({
    required String email,
    required String name,
    String? companyName,
    String? companyRole,
    String? companyCode,
    required List<Booking> bookings,
  }) async {
    try {
      await privateDB.collection('org_users').doc(email).set({
        'id': email,
        'name': name,
        'email': email,
        'companyName': companyName,
        'companyRole': companyRole,
        'companyCode': companyCode,
        'bookings': bookings.map((b) => b.toJson()).toList(),
        'lastMirrored': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
    } catch (_) {
      // mirror failure is non-fatal AAS
    }
  }

  // ─────────────────────────────────────────────────────────────────
  // COMBINED SYNC - public profile + mirror to private in one call
  // ─────────────────────────────────────────────────────────────────

  static Future<String?> fullSync() async {
    final err = await syncUserToPublic();
    if (err != null) return err;

    await mirrorUserToPrivate(
      email: Global.userEmail!,
      name: Global.userName ?? '',
      companyName: Global.companyName,
      companyRole: Global.companyRole,
      companyCode: Global.companyCode,
      bookings: Global.bookings,
    );

    return null;
  }
}
