// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_private.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultPrivateFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultPrivateFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultPrivateFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultPrivateFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultPrivateFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultPrivateFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8ZdOYyFCmgNJ0NmBpQntiFAtOo-LFcE',
    appId: '1:40874877867:web:d9d7a6b4073d937756a8ee',
    messagingSenderId: '40874877867',
    projectId: 'paperjournal-private',
    authDomain: 'paperjournal-private.firebaseapp.com',
    storageBucket: 'paperjournal-private.firebasestorage.app',
    measurementId: 'G-MPK6DXQG6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEiaTlvV9nu-WJnzuxIRFVuBYoTxli5aQ',
    appId: '1:40874877867:android:611458064e09d72856a8ee',
    messagingSenderId: '40874877867',
    projectId: 'paperjournal-private',
    storageBucket: 'paperjournal-private.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG8ZdOYyFCmgNJ0NmBpQntiFAtOo-LFcE',
    appId: '1:40874877867:web:d94dc6c11d36aa1656a8ee',
    messagingSenderId: '40874877867',
    projectId: 'paperjournal-private',
    authDomain: 'paperjournal-private.firebaseapp.com',
    storageBucket: 'paperjournal-private.firebasestorage.app',
    measurementId: 'G-BYTVN922GL',
  );
}
