// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_public.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultPublicFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultPublicFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultPublicFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultPublicFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultPublicFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultPublicFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcksRJ4p7_A7oBxmIqf1uoH-r4iBw_niI',
    appId: '1:429663002292:web:d7cca461b92260bb7101e1',
    messagingSenderId: '429663002292',
    projectId: 'paperjournal-public',
    authDomain: 'paperjournal-public.firebaseapp.com',
    storageBucket: 'paperjournal-public.firebasestorage.app',
    measurementId: 'G-C9VR7QZCKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjRl3KslNKfUXEiaD74pbB2Lq8uhmS66M',
    appId: '1:429663002292:android:3a485aab6c1747eb7101e1',
    messagingSenderId: '429663002292',
    projectId: 'paperjournal-public',
    storageBucket: 'paperjournal-public.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcksRJ4p7_A7oBxmIqf1uoH-r4iBw_niI',
    appId: '1:429663002292:web:42156af19edf3fdc7101e1',
    messagingSenderId: '429663002292',
    projectId: 'paperjournal-public',
    authDomain: 'paperjournal-public.firebaseapp.com',
    storageBucket: 'paperjournal-public.firebasestorage.app',
    measurementId: 'G-YVFT4DHPKN',
  );
}
