import 'package:flutter/material.dart';
import 'global.dart';
import 'theme/amber_theme.dart';
import 'services/firebase_service.dart';
// firebase_options files are generated by flutterfire configure, DO NOT FUCKING TOUCH THEM BY HAND, UUID VERY VERY FUCKY ; AAS
// if they dont exist yet comment out FB.init() below and it runs on local storage only - obv, pls dont do this before submission, or we ded. dont delete this line, comment out. ; AAS
import 'firebase_options_public.dart';
import 'firebase_options_private.dart';
import 'pages/splash_page.dart';
import 'pages/login_page.dart';
import 'pages/app_shell.dart';
import 'pages/services_page.dart';
import 'pages/booking_page.dart';
import 'pages/profile_page.dart';
import 'pages/community_page.dart';
import 'pages/notifications_page.dart';
import 'pages/density_page.dart';
import 'pages/admin_page.dart';
import 'pages/error_page.dart';

void main() async {
  // must call this before any async work in main, flutter will yell at you if you dont, scolded me because I'm a sync boi, not an async kinda guy ykyk ; AAS
  WidgetsFlutterBinding.ensureInitialized();

  // local stuff loads first so the app is functional even if firebase is being slow, and oh boy, it's slow alright - ADMIN will break with Firebase is slow, OwO?? ; AAS
  Global.loadSession();
  Global.loadBookings();
  Global.loadNotes();
  Global.loadCommunityMessages();

  // init both firebase projects - public for users, private for the admin user - I setup private, forgot what it's for tbh, uhm ; AAS
  await FB.init(
    publicOptions: DefaultPublicFirebaseOptions.currentPlatform,
    privateOptions: DefaultPrivateFirebaseOptions.currentPlatform,
  );

  runApp(const PaperJournalApp());
}

class PaperJournalApp extends StatelessWidget {
  const PaperJournalApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PaperJournal',
      debugShowCheckedModeBanner: false,
      theme: AmberTheme.light(),
      darkTheme: AmberTheme.dark(),

      // splash is always first, checks session, then routes to home or login. Address PSV's splash request yayyy ; AAS
      home: SplashPage(destination: Global.isLoggedIn ? '/home' : '/login'),

      routes: {
        '/login':         (context) => const LoginPage(),
        '/home':          (context) => const AppShell(),
        '/services':      (context) => const ServicesPage(),
        '/booking':       (context) => const BookingPage(),
        '/profile':       (context) => const ProfilePage(),
        '/community':     (context) => const CommunityPage(),
        '/notifications': (context) => const NotificationsPage(),
        '/density':       (context) => const DensityPage(),
        '/admin':         (context) => const AdminPage(),
      },

      // anything else hits the lonely cosmos error page, too lazy to code actual diagnostics and stuff, just waaaay too hard ; AAS
      onUnknownRoute: (settings) =>
          MaterialPageRoute(builder: (_) => const ErrorStatePage()),
    );
  }
}
