import 'package:flutter/material.dart';
import 'global.dart';
import 'theme/amber_theme.dart';
import 'services/firebase_service.dart';
// firebase_options_public.dart and firebase_options_private.dart are
// generated by flutterfire configure - dont write these by hand AAS
// if they dont exist yet just comment out the FB.init() call below and
// the app will run on local storage only until you set up firebase
import 'firebase_options_public.dart';
import 'firebase_options_private.dart';
import 'pages/splash_page.dart';
import 'pages/login_page.dart';
import 'pages/app_shell.dart';
import 'pages/services_page.dart';
import 'pages/booking_page.dart';
import 'pages/profile_page.dart';
import 'pages/community_page.dart';
import 'pages/notifications_page.dart';
import 'pages/density_page.dart';
import 'pages/admin_page.dart';
import 'pages/error_page.dart';

void main() async {
  // needed before any async work in main AAS
  WidgetsFlutterBinding.ensureInitialized();

  // load local state first so the app is usable even if firebase is slow
  Global.loadSession();
  Global.loadBookings();
  Global.loadNotes();
  Global.loadCommunityMessages();

  // init both firebase projects
  // if this throws, something is wrong with your firebase_options files
  // run: flutterfire configure --project=paperjournal-public --out=lib/firebase_options_public.dart
  // run: flutterfire configure --project=paperjournal-private --out=lib/firebase_options_private.dart
  await FB.init(
    publicOptions: DefaultPublicFirebaseOptions.currentPlatform,
    privateOptions: DefaultPrivateFirebaseOptions.currentPlatform,
  );

  runApp(const PaperJournalApp());
}

class PaperJournalApp extends StatelessWidget {
  const PaperJournalApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PaperJournal',
      debugShowCheckedModeBanner: false,
      theme: AmberTheme.light(),
      darkTheme: AmberTheme.dark(),

      // splash always first - checks session, shows loading bar, then navigates
      home: SplashPage(destination: Global.isLoggedIn ? '/home' : '/login'),

      routes: {
        '/login': (context) => const LoginPage(),
        '/home': (context) => const AppShell(),
        '/services': (context) => const ServicesPage(),
        '/booking': (context) => const BookingPage(),
        '/profile': (context) => const ProfilePage(),
        '/community': (context) => const CommunityPage(),
        '/notifications': (context) => const NotificationsPage(),
        '/density': (context) => const DensityPage(),
        '/admin': (context) => const AdminPage(),
      },

      onUnknownRoute: (settings) =>
          MaterialPageRoute(builder: (_) => const ErrorStatePage()),
    );
  }
}
